import Foundation

/// Writes a sourceable shell snippet reflecting the active proxy, so that CLI
/// tools (curl, git, npm, …) — which ignore the macOS system proxy — pick up
/// the same setting. Source it from ~/.zshrc:
///
///     [ -f ~/.config/proxy-switcher/env.sh ] && source ~/.config/proxy-switcher/env.sh
///
/// The file always starts by unsetting the proxy variables, then exports them
/// only when a proxy is active, so sourcing it always yields a correct state.
struct ShellEnvWriter {
    private let fileURL: URL

    /// Variables we manage, listed for the leading `unset`.
    private let managedVars = [
        "ALL_PROXY", "HTTP_PROXY", "HTTPS_PROXY",
        "all_proxy", "http_proxy", "https_proxy",
        "NO_PROXY", "no_proxy",
    ]

    init() {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let dir = home.appendingPathComponent(".config/proxy-switcher", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        self.fileURL = dir.appendingPathComponent("env.sh")
    }

    var path: String { fileURL.path }

    /// Regenerate env.sh for the given active profile (nil / off → proxy unset).
    func write(profile: ProxyProfile?, ssid: String?) {
        var lines: [String] = [
            "# Auto-generated by Proxy Switcher — do not edit.",
            "# Network: \(ssid ?? "no Wi-Fi")   Proxy: \(profile?.summary ?? "off")",
            "unset \(managedVars.joined(separator: " "))",
        ]

        if let url = proxyURL(for: profile) {
            lines += [
                "export ALL_PROXY=\"\(url)\"",
                "export HTTP_PROXY=\"$ALL_PROXY\"",
                "export HTTPS_PROXY=\"$ALL_PROXY\"",
                "export all_proxy=\"$ALL_PROXY\" http_proxy=\"$ALL_PROXY\" https_proxy=\"$ALL_PROXY\"",
                "export NO_PROXY=\"localhost,127.0.0.1,::1,*.local\"",
                "export no_proxy=\"$NO_PROXY\"",
            ]
        } else if profile?.type == .pac {
            lines.append("# PAC proxies can't be expressed as CLI env vars; left unset.")
        }

        let content = lines.joined(separator: "\n") + "\n"
        try? content.data(using: .utf8)?.write(to: fileURL, options: .atomic)
    }

    /// Build the proxy URL string for env vars, or nil if there's nothing to set.
    private func proxyURL(for profile: ProxyProfile?) -> String? {
        guard let p = profile, p.enabled else { return nil }

        let scheme: String
        switch p.type {
        case .socks:        scheme = "socks5h"   // resolve DNS at the proxy
        case .http, .https: scheme = "http"      // proxy is reached over HTTP
        case .off, .pac:    return nil           // PAC handled by caller
        }

        var auth = ""
        if !p.username.isEmpty {
            let user = p.username.addingPercentEncoding(withAllowedCharacters: .urlUserAllowed) ?? p.username
            let pass = p.password.addingPercentEncoding(withAllowedCharacters: .urlPasswordAllowed) ?? p.password
            auth = pass.isEmpty ? "\(user)@" : "\(user):\(pass)@"
        }
        return "\(scheme)://\(auth)\(p.host):\(p.port)"
    }
}
